/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;


import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author marky
 */
public class History extends javax.swing.JFrame {
  Connection con;
   PreparedStatement pst;
   ResultSet rs=null;
    
     
    public History() {
        initComponents();
          String url= "jdbc:mysql://localhost/ab_database";
        String user="root";
        String pass="";
        try{
            con = DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error: "+ ex.getMessage());
        }
        updateDB();
         table.getColumnModel().getColumn(0).setPreferredWidth(1);
         table.getColumnModel().getColumn(1).setPreferredWidth(1);
         table.getColumnModel().getColumn(2).setPreferredWidth(150);
         table.getColumnModel().getColumn(3).setPreferredWidth(150);
         table.getColumnModel().getColumn(4).setPreferredWidth(1);
         table.getColumnModel().getColumn(5).setPreferredWidth(1);
         table.getColumnModel().getColumn(6).setPreferredWidth(10);
         table.getColumnModel().getColumn(7).setPreferredWidth(1);
          table.getColumnModel().getColumn(8).setPreferredWidth(1);
           table.getColumnModel().getColumn(9).setPreferredWidth(150);
            table.getColumnModel().getColumn(10).setPreferredWidth(100);
            table.getColumnModel().getColumn(11).setPreferredWidth(100);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        sr = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 606));
        jPanel1.setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Pid", "Name", "Type", "Prev Quantity", "New Quantity", "Quantity A/S", "Price", "Status", "Info", "Person in Charge", "Date & Time"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 1240, 430);

        sr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                srKeyPressed(evt);
            }
        });
        jPanel1.add(sr);
        sr.setBounds(150, 80, 850, 26);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Update");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1100, 80, 80, 30);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(1010, 80, 76, 27);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Record Page");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(550, 40, 80, 17);

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(1190, 80, 76, 27);

        id.setText("jTextField1");
        jPanel1.add(id);
        id.setBounds(840, 270, 75, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/Untitled design (2).png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 1920, 620);

        pid.setForeground(new java.awt.Color(0, 0, 0));
        pid.setText("jLabel3");
        jPanel1.add(pid);
        pid.setBounds(100, 120, 37, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srKeyPressed
     DefaultTableModel obj=(DefaultTableModel)table.getModel();
    TableRowSorter<DefaultTableModel> obj1=new TableRowSorter<>(obj);
    table.setRowSorter(obj1);
    obj1.setRowFilter(RowFilter.regexFilter(sr.getText()));
    }//GEN-LAST:event_srKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     Update ac = new Update();
     ac.setVisible(true);
     ac.setLocationRelativeTo(null);
     dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Table ad = new Table();
     ad.setVisible(true);
     ad.setLocationRelativeTo(null);
     dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      int id=Integer.parseInt(table.getValueAt(table.getSelectedRow(),0).toString());
  try{
      Class.forName("com.mysql.cj.jdbc.Driver");
    con =DriverManager.getConnection("jdbc:mysql://localhost/ab_database", "root","");
    Statement st=con.createStatement();
    int r=JOptionPane.showConfirmDialog(this, "are you sure delete selected row?");
    if(r==0){
        if(!st.execute("DELETE FROM prod_record WHERE id="+id)){
          updateDB();
         
        }
    }else{
        JOptionPane.showMessageDialog(this, "Error!try again.");
    }
   }catch(Exception e){
           e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
 int id=Integer.parseInt(table.getValueAt(table.getSelectedRow(),0).toString());
  try{
       Class.forName("com.mysql.cj.jdbc.Driver");
    con =DriverManager.getConnection("jdbc:mysql://localhost/ab_database", "root","");
    Statement st=con.createStatement();
    rs = st.executeQuery("SELECT * FROM prod_record WHERE id="+id);
    while(rs.next()){
        pid.setText(rs.getString("id"));
       
    }
  }catch(Exception ex){
            System.out.println("Error: "+ ex.getMessage());
  }   
    }//GEN-LAST:event_tableMouseClicked
public void updateDB(){
       String sql="SELECT * FROM prod_record";
          try{
         PreparedStatement pst = con.prepareStatement(sql);
         ResultSet rs=pst.executeQuery();
         DefaultTableModel model= (DefaultTableModel)table.getModel();
         model.setRowCount(0);
         while(rs.next()){
             model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12)});
         }
        }catch(Exception ex){
            System.out.println("Error: "+ ex.getMessage());
            
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(History.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new History().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pid;
    private javax.swing.JTextField sr;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
