/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
public class Table extends javax.swing.JFrame {

    
   Connection con;
   PreparedStatement pst;
   ResultSet rs=null;
   
    public Table() {
        initComponents();
        String url= "jdbc:mysql://localhost/ab_database";
        String user="root";
        String pass="";
        try{
            con = DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error: "+ ex.getMessage());
        }
        updateDB();
        curdateTime();
      id.setVisible(false);
         dbtable.getColumnModel().getColumn(0).setPreferredWidth(1);
         dbtable.getColumnModel().getColumn(1).setPreferredWidth(120);
         dbtable.getColumnModel().getColumn(2).setPreferredWidth(120);
         dbtable.getColumnModel().getColumn(3).setPreferredWidth(10);
         dbtable.getColumnModel().getColumn(4).setPreferredWidth(10);
         dbtable.getColumnModel().getColumn(5).setPreferredWidth(70);
         in.setText("Deleted");
         info.setText("deleted");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dbtable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        nm = new javax.swing.JTextField();
        tp = new javax.swing.JTextField();
        qn = new javax.swing.JTextField();
        pr = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        sr = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        in = new javax.swing.JTextField();
        info = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        dbtable.setBackground(new java.awt.Color(204, 204, 204));
        dbtable.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        dbtable.setForeground(new java.awt.Color(0, 0, 0));
        dbtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Type", "Quantity", "Price", "Date"
            }
        ));
        dbtable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        dbtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dbtable);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(220, 110, 740, 406);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Add");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setPreferredSize(new java.awt.Dimension(80, 27));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 380, 80, 30);

        nm.setBackground(new java.awt.Color(153, 153, 153));
        nm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nm.setForeground(new java.awt.Color(0, 0, 0));
        nm.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(nm);
        nm.setBounds(70, 130, 100, 30);

        tp.setBackground(new java.awt.Color(153, 153, 153));
        tp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tp.setForeground(new java.awt.Color(0, 0, 0));
        tp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(tp);
        tp.setBounds(70, 200, 100, 30);

        qn.setBackground(new java.awt.Color(153, 153, 153));
        qn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        qn.setForeground(new java.awt.Color(0, 0, 0));
        qn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        qn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qnActionPerformed(evt);
            }
        });
        qn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qnKeyPressed(evt);
            }
        });
        jPanel1.add(qn);
        qn.setBounds(70, 260, 100, 30);

        pr.setBackground(new java.awt.Color(153, 153, 153));
        pr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pr.setForeground(new java.awt.Color(0, 0, 0));
        pr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prKeyPressed(evt);
            }
        });
        jPanel1.add(pr);
        pr.setBounds(70, 326, 100, 30);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Delete");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setPreferredSize(new java.awt.Dimension(80, 27));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 430, 80, 27);

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Edit");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setPreferredSize(new java.awt.Dimension(80, 27));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(130, 380, 79, 30);

        sr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                srKeyPressed(evt);
            }
        });
        jPanel1.add(sr);
        sr.setBounds(310, 80, 540, 26);

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Records");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton6.setPreferredSize(new java.awt.Dimension(80, 27));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(80, 470, 80, 27);

        jButton7.setBackground(new java.awt.Color(102, 102, 102));
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("Sign Out");
        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton7.setPreferredSize(new java.awt.Dimension(80, 27));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(130, 430, 80, 30);

        time.setBackground(new java.awt.Color(255, 255, 255));
        time.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(time);
        time.setBounds(860, 10, 142, 20);
        jPanel1.add(in);
        in.setBounds(680, 140, 68, 26);
        jPanel1.add(info);
        info.setBounds(740, 170, 68, 26);

        id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        id.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(id);
        id.setBounds(80, 90, 0, 0);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 80, 0, 0);

        pid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/Stocks (3).png"))); // NOI18N
        jPanel1.add(pid);
        pid.setBounds(0, 0, 980, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void updateDB(){
       String sql="SELECT * FROM prod_table";
          try{
         PreparedStatement pst = con.prepareStatement(sql);
         ResultSet rs=pst.executeQuery();
         DefaultTableModel model= (DefaultTableModel)dbtable.getModel();
         model.setRowCount(0);
         while(rs.next()){
             model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
         }
        }catch(Exception ex){
            System.out.println("Error: "+ ex.getMessage());
            
        }
}
public void curdateTime(){
    DateTimeFormatter dtf= DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
    LocalDateTime now= LocalDateTime.now();
    time.setText(dtf.format(now));
}

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String piValue = JOptionPane.showInputDialog(this, "Enter a name for variable pi:");

// Check if piValue is null
if (piValue == null) {
    JOptionPane.showMessageDialog(this, "Operation canceled by user. No changes made.");
    return; // Stop further execution
}
        String nadd="New Product";
        try{
              String nmValue = nm.getText();
    String tpValue = tp.getText();
    String qnValue = qn.getText();
    String prValue = pr.getText();

    if (nmValue.isEmpty() || tpValue.isEmpty() || qnValue.isEmpty() || prValue.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all fields before adding data.");
        return; 
    }
      String sql="INSERT INTO `prod_table`(Name, Type, Quantity, Price, DateTime) VALUES (?,?,?,?,?)";
      con =DriverManager.getConnection("jdbc:mysql://localhost/ab_database", "root","");
      pst= con.prepareStatement(sql);
      int r=JOptionPane.showConfirmDialog(this, "are you sure to Add these Data?");
        if(r==0){
      pst.setString(1, nm.getText());
      pst.setString(2, tp.getText());
      pst.setString(3, qn.getText());
      pst.setString(4, pr.getText());
      pst.setString(5, time.getText());
      pst.executeUpdate();
          

        int confirmSaveToOtherDB = JOptionPane.showConfirmDialog(this, "Do you want to save the changes to another database?", "Confirmation", JOptionPane.YES_NO_OPTION);

    if (confirmSaveToOtherDB == JOptionPane.YES_OPTION) {
       String sqql = "INSERT INTO prod_record(pid, Name, Type, Prev_Quan, Quan, Qa_s, price, in_out, info, Pio, Date) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
        try (Connection conSecondDB = DriverManager.getConnection("jdbc:mysql://localhost/ab_database", "root", "");
             PreparedStatement pstSecondDB = conSecondDB.prepareStatement(sqql)) {

            pstSecondDB.setString(1, pid.getText());
            pstSecondDB.setString(2, nm.getText());
            pstSecondDB.setString(3, tp.getText());
            pstSecondDB.setString(4, qn.getText());
            pstSecondDB.setString(5, nadd);
            pstSecondDB.setString(6, nadd);
            pstSecondDB.setString(7, pr.getText());
            pstSecondDB.setString(8, nadd);
            pstSecondDB.setString(9, nadd);

            pstSecondDB.setString(10, piValue);
            pstSecondDB.setString(11, time.getText());

            // Execute the second database insertion
            pstSecondDB.executeUpdate();

            JOptionPane.showMessageDialog(this, "Updated Successfully");
            // ... (rest of the code remains unchanged)
        } catch (SQLException ex) {
            System.out.println("Error in second database insertion: " + ex.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Error! Try again.");
        return;
    }
        }
} catch (Exception ex) {
    System.out.println("Error: " + ex.getMessage());
}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String piValue = JOptionPane.showInputDialog(this, "Enter a name for variable pi:");

// Check if piValue is null
if (piValue == null) {
    JOptionPane.showMessageDialog(this, "Operation canceled by user. No changes made.");
    return; // Stop further execution
}

int id = Integer.parseInt(dbtable.getValueAt(dbtable.getSelectedRow(), 0).toString());
String Delete = "Deleted";

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    con = DriverManager.getConnection("jdbc:mysql://localhost/ab_database", "root", "");
    Statement st = con.createStatement();

    // Move the deletion confirmation inside this block
    int r = JOptionPane.showConfirmDialog(this, "Are you sure to delete the selected row?");

    if (r == 0) {
        if (!st.execute("DELETE FROM prod_table WHERE id=" + id)) {
            int confirmSaveToOtherDB = JOptionPane.showConfirmDialog(this, "Do you want to save the changes to another database?", "Confirmation", JOptionPane.YES_NO_OPTION);

            if (confirmSaveToOtherDB == JOptionPane.YES_OPTION) {
                String sql = "INSERT INTO prod_record(pid, Name, Type, Prev_Quan, Quan, Qa_s, price, in_out, info, Pio, Date) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
                con = DriverManager.getConnection("jdbc:mysql://localhost/ab_database", "root", "");
                pst = con.prepareStatement(sql);

                pst.setString(1, pid.getText());
                pst.setString(2, nm.getText());
                pst.setString(3, tp.getText());
                pst.setString(4, qn.getText());
                pst.setString(5, Delete);
                pst.setString(6, Delete);
                pst.setString(7, pr.getText());
                pst.setString(8, in.getText());
                pst.setString(9, info.getText());

                pst.setString(10, piValue);
                pst.setString(11, time.getText());

                // Move the deletion inside this block
                if (!st.execute("DELETE FROM prod_table WHERE id=" + id)) {
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Updated Successfully");
                    nm.setText("");
                    tp.setText("");
                    qn.setText("");
                    pr.setText("");
                    in.setText("");
                    info.setText("");
                    updateDB();
                } else {
                    JOptionPane.showMessageDialog(this, "Error occurred during deletion. No changes made.");
                    return;
                }
            }

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Updated Successfully");
            nm.setText("");
            tp.setText("");
            qn.setText("");
            pr.setText("");
            in.setText("");
            info.setText("");
            updateDB();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Error! Try again.");
    }
} catch (Exception e) {
    e.printStackTrace();
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void dbtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbtableMouseClicked
  int id=Integer.parseInt(dbtable.getValueAt(dbtable.getSelectedRow(),0).toString());
  try{
       Class.forName("com.mysql.cj.jdbc.Driver");
    con =DriverManager.getConnection("jdbc:mysql://localhost/ab_database", "root","");
    Statement st=con.createStatement();
    rs = st.executeQuery("SELECT * FROM prod_table WHERE id="+id);
    while(rs.next()){
        pid.setText(rs.getString("id"));
        nm.setText(rs.getString("Name"));
        tp.setText(rs.getString("Type"));
        qn.setText(rs.getString("Quantity"));
        pr.setText(rs.getString("Price"));
    }
  }catch(Exception ex){
            System.out.println("Error: "+ ex.getMessage());
  }
    }//GEN-LAST:event_dbtableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Update ap = new Update();
ap.setVisible(true);
ap.setLocationRelativeTo(null);
dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void qnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qnActionPerformed

    private void qnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qnKeyPressed
    char c = evt.getKeyChar();
    if(Character.isLetter(c)){
        qn.setEditable(false);
        JOptionPane.showMessageDialog(this,"Please Input Numbers Only!!!!");
    }else{
        qn.setEditable(true);
    }
    }//GEN-LAST:event_qnKeyPressed

    private void prKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prKeyPressed
      char c = evt.getKeyChar();
    if(Character.isLetter(c)){
        pr.setEditable(false);
        JOptionPane.showMessageDialog(this,"Please Input Numbers Only!!!!");
    }else{
        pr.setEditable(true);
    }
    }//GEN-LAST:event_prKeyPressed

    private void srKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srKeyPressed
    DefaultTableModel obj=(DefaultTableModel)dbtable.getModel();
    TableRowSorter<DefaultTableModel> obj1=new TableRowSorter<>(obj);
    dbtable.setRowSorter(obj1);
    obj1.setRowFilter(RowFilter.regexFilter(sr.getText()));
    }//GEN-LAST:event_srKeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     History ab = new History();
     ab.setVisible(true);
     ab.setLocationRelativeTo(null);
     dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    Login af= new Login();
    af.setVisible(true);
    af.setLocationRelativeTo(null);
    dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dbtable;
    private javax.swing.JLabel id;
    private javax.swing.JTextField in;
    private javax.swing.JTextField info;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nm;
    private javax.swing.JLabel pid;
    private javax.swing.JTextField pr;
    private javax.swing.JTextField qn;
    private javax.swing.JTextField sr;
    private javax.swing.JLabel time;
    private javax.swing.JTextField tp;
    // End of variables declaration//GEN-END:variables
}
